version: '3'
services:
  #nginx:
   #image: nginx
   #ports:
   #  - "80:80"
   #volumes:
   #  - ./nginx.conf:/etc/nginx/nginx.conf:ro
   #links:
   #  - backend
   #  - app
   #  - admin
   #restart: on-failure:5
 
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: W7swsa1jKwlo6veszX3Q
      #    volumes: 
#      - ./data/db:/data/db

  
